workflow:
  rules:
    - if: '$CI_MERGE_REQUEST_ID != null'
      when: never
    - when: always

stages:
  - publish

image: hseeberger/scala-sbt:11.0.4_1.3.2_2.12.10

before_script:
  - gpg --import  <(echo "$GITLAB_PGP_PRIVATE_KEY")
  - export APPLICATION=${APPLICATION:-"$(echo $CI_PROJECT_NAME | tr '[:upper:]' '[:lower:]')"}
  - export DOCKER_IMAGE=$DOCKER_REGISTRY/$APPLICATION
  - export DOCKER_IMAGE_SHA=$DOCKER_IMAGE:${CI_COMMIT_SHORT_SHA}
  - export DOCKER_IMAGE_VERSION=$DOCKER_IMAGE:${VERSION}


publish on gitlab:
  rules:
    - if: '$CI_COMMIT_TAG != null'
      when: on_success
  stage: publish
  script:
    - sbt ";+publishSigned ;sonatypeBundleRelease"
  tags:
    - aws
