stages:
  - test
  - publish

sbt test:
  stage: test
  script:
    - sbt test

publish on bintray:
  stage: publish
  only:
    - master
  script:
    - sbt -Dbintray.user=tyrcho -Dbintray.pass=$BINTRAY_API_KEY publish

image: hseeberger/scala-sbt:11.0.3_1.2.8_2.12.8
variables:
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/sbtboot -Dsbt.boot.directory=sbt-cache/boot -Dsbt.ivy.home=sbt-cache/ivy"
  COURSIER_CACHE: "sbt-cache/coursier"
cache:
  key: "sbt-$CI_BUILD_REF_NAME"
  paths:
    - sbt-cache
