include:
  - 'https://gitlab.com/colisweb-open-source/ci-common/raw/v13.0.0/templates/scala.yml'

test approvals-scala:
  extends: .sbt-test
  tags:
   - aws
  before_script: []

version:
  extends: .version
  tags:
    - aws

publish approvals:
  extends: .bintray-publish
  script:
    - sbt ";+publishSigned ;sonatypeBundleRelease"
  tags:
    - aws