include:
  - 'https://colisweb-open-source.gitlab.io/ci-common/templates/scala.yml'

compile approvals-scala:
  extends: .sbt-compile-cross

test approvals-scala:
  extends: .sbt-test-cross
  tags:
   - aws

version approvals-scala:
  extends: .version
  tags:
    - aws

publish approvals-scala:
  extends: .sonatype-publish
  tags:
    - aws
