include:
  - 'https://gitlab.com/colisweb-open-source/ci-common/raw/v9.1.1/templates/scala.yml'

test approvals-scala:
  extends: .sbt-test
  tags: []
  before_script: []

# deactivated, strange behaviour with scalatest 3.2.0
#unused-dependencies:
#  extends: .sbt-unused-dependencies
#  tags: []
#  before_script: []

version:
  extends: .version
  tags: []

publish on gitlab:
  stage: publish
  only:
    - master
  script:
    - sbt "+ publish"

image: hseeberger/scala-sbt:11.0.4_1.3.2_2.12.10
variables:
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/sbtboot -Dsbt.boot.directory=sbt-cache/boot -Dsbt.ivy.home=sbt-cache/ivy"
  COURSIER_CACHE: "sbt-cache/coursier"
cache:
  key: "sbt-$CI_BUILD_REF_NAME"
  paths:
    - sbt-cache
