include:
  - 'https://gitlab.com/colisweb-open-source/ci-common/raw/v8.0.1/templates/scala.yml'

test approvals-scala:
  extends: .sbt-test
  tags: []

unused-dependencies:
  extends: .sbt-unused-dependencies
  tags: []

version:
  extends: .version
  tags: []

publish on bintray:
  extends: .bintray-publish
  tags: []
