include:
  - https://colisweb-idl.gitlab.io/colisweb-open-source/ci-common/v17.7.0/templates/scala.yml

compile approvals-scala:
  extends: .sbt-compile-cross

test approvals-scala:
  extends: .sbt-test-cross
  tags:
   - aws

version approvals-scala:
  extends: .version
  tags:
    - aws

publish approvals-scala:
  extends: .sonatype-publish
  tags:
    - aws
