include:
  - 'https://gitlab.com/colisweb-open-source/ci-common/raw/v9.1.1/templates/scala.yml'

version:
  extends: .version
  tags: []

publish on gitlab:
  extends: .rules-except-for-tags
  tags:
    - aws
  stage: publish
  script:
    - sbt "+publishSigned"

image: hseeberger/scala-sbt:11.0.4_1.3.2_2.12.10
variables:
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/sbtboot -Dsbt.boot.directory=sbt-cache/boot -Dsbt.ivy.home=sbt-cache/ivy"
  COURSIER_CACHE: "sbt-cache/coursier"
cache:
  key: "sbt-$CI_BUILD_REF_NAME"
  paths:
    - sbt-cache
